name: matchmaker
description: A pure Dart package for video game skill rating. This package implements the Glicko-2 rating system for accurate player skill assessment.
version: 0.1.0
repository: https://github.com/ricardodalarme/matchmaker

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
